export interface City {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  intro: string;
  neighborhoods: string[];
  suburbs: string[];
  zipCodes: string[];
  localNote?: string;
  tier: 1 | 2 | 3;
}

export const cities: City[] = [
  {
    slug: 'austin-tx',
    name: 'Austin',
    state: 'Texas',
    stateAbbr: 'TX',
    tier: 1,
    intro: 'Austin\'s thriving tech scene and growing population demand top-tier AV and smart home solutions. From downtown lofts to hill country estates, Beacon AV serves all of Austin and surrounding areas with same-week availability.',
    neighborhoods: ['Downtown', 'South Congress', 'East Austin', 'West Lake Hills', 'Zilker', 'Mueller'],
    suburbs: ['Cedar Park', 'Round Rock', 'Pflugerville', 'Leander', 'Lakeway'],
    zipCodes: ['78701', '78702', '78703', '78704', '78705', '78721', '78722', '78723', '78741', '78745', '78746', '78751', '78757', '78758', '78759'],
    localNote: 'Austin installers specialize in high-end residential automation and commercial AV for tech companies.',
  },
  {
    slug: 'new-york-ny',
    name: 'New York',
    state: 'New York',
    stateAbbr: 'NY',
    tier: 1,
    intro: 'From Manhattan penthouses to Brooklyn townhouses, Beacon AV serves all five boroughs and surrounding areas. We specialize in pre-war apartment challenges and luxury residential installations.',
    neighborhoods: ['Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island'],
    suburbs: ['Westchester', 'Long Island', 'New Jersey'],
    zipCodes: ['10001', '10002', '10003', '10004', '10005', '10006', '10007', '10008', '10009', '10010'],
    localNote: 'NYC installers experienced with pre-war construction, basement AV closets, and luxury finishes.',
  },
  {
    slug: 'los-angeles-ca',
    name: 'Los Angeles',
    state: 'California',
    stateAbbr: 'CA',
    tier: 1,
    intro: 'LA\'s entertainment industry drives demand for high-end AV and smart home systems. Beacon AV serves the entire greater LA area with specialists in residential, commercial, and entertainment venues.',
    neighborhoods: ['West Hollywood', 'Beverly Hills', 'Bel Air', 'Brentwood', 'Pacific Palisades', 'Santa Monica'],
    suburbs: ['Pasadena', 'Santa Clarita', 'Long Beach', 'Irvine'],
    zipCodes: ['90001', '90002', '90003', '90004', '90005', '90006', '90007', '90008', '90009', '90010'],
    localNote: 'LA team handles high-end residential, entertainment venues, and large-scale commercial installations.',
  },
  {
    slug: 'chicago-il',
    name: 'Chicago',
    state: 'Illinois',
    stateAbbr: 'IL',
    tier: 1,
    intro: 'Chicago\'s mix of historic lofts and modern high-rises drives diverse AV and automation needs. Beacon AV serves downtown, all neighborhoods, and suburbs with fast turnaround.',
    neighborhoods: ['Loop', 'River North', 'West Loop', 'Lincoln Park', 'Wicker Park', 'Hyde Park'],
    suburbs: ['Evanston', 'Naperville', 'Schaumburg', 'Oak Park'],
    zipCodes: ['60601', '60602', '60603', '60604', '60605', '60606', '60607', '60608', '60609', '60610'],
    localNote: 'Chicago installers experienced with loft challenges, historic building constraints, and high-rise logistics.',
  },
  {
    slug: 'dallas-tx',
    name: 'Dallas',
    state: 'Texas',
    stateAbbr: 'TX',
    tier: 1,
    intro: 'Dallas\'s corporate headquarters and upscale residential market drive strong demand for commercial and residential AV. Fast installs across Dallas and suburbs.',
    neighborhoods: ['Downtown', 'Uptown', 'Highland Park', 'University Park', 'Preston Hollow', 'Oak Lawn'],
    suburbs: ['Arlington', 'Plano', 'Irving', 'Frisco', 'Garland'],
    zipCodes: ['75001', '75002', '75006', '75007', '75009', '75010', '75019', '75020', '75021', '75022'],
  },
  {
    slug: 'miami-fl',
    name: 'Miami',
    state: 'Florida',
    stateAbbr: 'FL',
    tier: 1,
    intro: 'Miami\'s luxury real estate market demands high-end AV and smart home automation. Beacon AV serves Miami-Dade, Broward, and surrounding areas.',
    neighborhoods: ['Brickell', 'Coconut Grove', 'Coral Gables', 'Wynwood', 'Design District', 'South Pointe'],
    suburbs: ['Coral Springs', 'Fort Lauderdale', 'Aventura', 'Doral'],
    zipCodes: ['33101', '33102', '33103', '33104', '33105', '33106', '33107', '33109', '33110', '33111'],
  },
  {
    slug: 'san-francisco-ca',
    name: 'San Francisco',
    state: 'California',
    stateAbbr: 'CA',
    tier: 1,
    intro: 'San Francisco\'s tech-savvy residents and commercial enterprises drive innovation in AV and smart home automation. We serve SF and Bay Area suburbs.',
    neighborhoods: ['Downtown', 'SOMA', 'Mission', 'Castro', 'Hayes Valley', 'Pacific Heights'],
    suburbs: ['Oakland', 'Berkeley', 'Palo Alto', 'San Mateo'],
    zipCodes: ['94102', '94103', '94104', '94105', '94107', '94108', '94109', '94110', '94111', '94112'],
  },
  {
    slug: 'houston-tx',
    name: 'Houston',
    state: 'Texas',
    stateAbbr: 'TX',
    tier: 1,
    intro: 'Houston\'s energy industry wealth and sprawling geography drive demand for quality AV and automation. Beacon AV serves all of greater Houston.',
    neighborhoods: ['Downtown', 'Memorial', 'Uptown', 'Montrose', 'River Oaks', 'Heights'],
    suburbs: ['Sugar Land', 'The Woodlands', 'Katy', 'League City'],
    zipCodes: ['77001', '77002', '77003', '77004', '77005', '77006', '77007', '77008', '77009', '77010'],
  },
  {
    slug: 'phoenix-az',
    name: 'Phoenix',
    state: 'Arizona',
    stateAbbr: 'AZ',
    tier: 1,
    intro: 'Phoenix\'s fast-growing population and new construction create strong demand for smart home and AV installations. Same-day quotes available.',
    neighborhoods: ['Downtown', 'Arcadia', 'Scottsdale', 'Paradise Valley', 'Ahwatukee', 'Maryvale'],
    suburbs: ['Tempe', 'Mesa', 'Chandler', 'Gilbert'],
    zipCodes: ['85001', '85002', '85003', '85004', '85005', '85006', '85007', '85008', '85009', '85010'],
  },
  {
    slug: 'denver-co',
    name: 'Denver',
    state: 'Colorado',
    stateAbbr: 'CO',
    tier: 1,
    intro: 'Denver\'s outdoor-focused lifestyle and growing tech scene drive demand for quality AV, smart home, and networking. Fast installs across the Front Range.',
    neighborhoods: ['Downtown', 'Capitol Hill', 'Highlands', 'LoDo', 'Cherry Creek', 'South Platte'],
    suburbs: ['Boulder', 'Littleton', 'Lakewood', 'Aurora'],
    zipCodes: ['80202', '80203', '80204', '80205', '80206', '80207', '80209', '80210', '80211', '80212'],
  },
  {
    slug: 'seattle-wa',
    name: 'Seattle',
    state: 'Washington',
    stateAbbr: 'WA',
    tier: 1,
    intro: 'Seattle\'s tech-centric population and rainy climate drive strong demand for smart home automation and quality AV systems. Beacon AV serves Seattle and greater Puget Sound.',
    neighborhoods: ['Downtown', 'Fremont', 'Capitol Hill', 'Queen Anne', 'Ballard', 'University District'],
    suburbs: ['Bellevue', 'Redmond', 'Tacoma', 'Kirkland'],
    zipCodes: ['98101', '98102', '98103', '98104', '98105', '98106', '98107', '98109', '98112', '98115'],
  },
  {
    slug: 'atlanta-ga',
    name: 'Atlanta',
    state: 'Georgia',
    stateAbbr: 'GA',
    tier: 1,
    intro: 'Atlanta\'s thriving corporate and entertainment scene drives demand for commercial and high-end residential AV. Fast turnaround across all metro areas.',
    neighborhoods: ['Downtown', 'Buckhead', 'Virginia Highland', 'Midtown', 'East Atlanta', 'West End'],
    suburbs: ['Sandy Springs', 'Alpharetta', 'Marietta', 'Kennesaw'],
    zipCodes: ['30303', '30307', '30308', '30309', '30310', '30312', '30313', '30314', '30315', '30316'],
  },
  {
    slug: 'boston-ma',
    name: 'Boston',
    state: 'Massachusetts',
    stateAbbr: 'MA',
    tier: 2,
    intro: 'Boston\'s historic neighborhoods and modern suburbs both need AV and smart home expertise. Beacon AV serves all of greater Boston.',
    neighborhoods: ['Back Bay', 'Beacon Hill', 'Downtown', 'South End', 'Cambridge', 'Brookline'],
    suburbs: ['Cambridge', 'Newton', 'Waltham', 'Quincy'],
    zipCodes: ['02101', '02102', '02103', '02104', '02105', '02106', '02108', '02109', '02110', '02111'],
    tier: 2,
  },
  {
    slug: 'washington-dc',
    name: 'Washington',
    state: 'D.C.',
    stateAbbr: 'DC',
    tier: 2,
    intro: 'Washington DC and the surrounding metro area have strong demand for commercial AV and residential smart homes. Same-week availability in most cases.',
    neighborhoods: ['Downtown', 'Georgetown', 'Capitol Hill', 'Dupont Circle', 'Navy Yard', 'Foggy Bottom'],
    suburbs: ['Arlington', 'Alexandria', 'Bethesda', 'Silver Spring'],
    zipCodes: ['20001', '20002', '20003', '20004', '20005', '20006', '20007', '20008', '20009', '20010'],
    tier: 2,
  },
  {
    slug: 'san-diego-ca',
    name: 'San Diego',
    state: 'California',
    stateAbbr: 'CA',
    tier: 2,
    intro: 'San Diego\'s temperate climate and outdoor lifestyle drive demand for outdoor AV and smart home systems. We serve San Diego County.',
    neighborhoods: ['Downtown', 'Gaslamp Quarter', 'Pacific Beach', 'La Jolla', 'Hillcrest', 'Ocean Beach'],
    suburbs: ['Carlsbad', 'Encinitas', 'Del Mar', 'Solana Beach'],
    zipCodes: ['92101', '92102', '92103', '92104', '92105', '92106', '92107', '92108', '92109', '92110'],
    tier: 2,
  },
  {
    slug: 'portland-or',
    name: 'Portland',
    state: 'Oregon',
    stateAbbr: 'OR',
    tier: 2,
    intro: 'Portland\'s tech-minded residents and eco-conscious culture drive demand for sustainable AV and smart home solutions. We serve Portland and surrounding areas.',
    neighborhoods: ['Downtown', 'Pearl District', 'Eastside', 'Hawthorne', 'Brooklyn', 'Division'],
    suburbs: ['Beaverton', 'Lake Oswego', 'Tigard', 'Oregon City'],
    zipCodes: ['97201', '97202', '97204', '97205', '97206', '97214', '97215', '97216', '97217', '97218'],
    tier: 2,
  },
  {
    slug: 'minneapolis-mn',
    name: 'Minneapolis',
    state: 'Minnesota',
    stateAbbr: 'MN',
    tier: 2,
    intro: 'Minneapolis-St. Paul metro area has strong demand for whole-home automation and commercial AV systems. Beacon AV serves Twin Cities and suburbs.',
    neighborhoods: ['Downtown', 'Northeast', 'Southeast', 'Southwest', 'Uptown', 'Phillips'],
    suburbs: ['St. Paul', 'Edina', 'Bloomington', 'Plymouth'],
    zipCodes: ['55401', '55402', '55403', '55404', '55405', '55406', '55407', '55408', '55409', '55410'],
    tier: 2,
  },
  {
    slug: 'miami-beach-fl',
    name: 'Miami Beach',
    state: 'Florida',
    stateAbbr: 'FL',
    tier: 2,
    intro: 'Miami Beach\'s resort and residential luxury market drives demand for high-end AV and smart home systems. 24-48 hour availability.',
    neighborhoods: ['South Beach', 'Mid-Beach', 'North Beach', 'Surfside', 'Bal Harbour', 'Downtown'],
    suburbs: ['Aventura', 'Sunny Isles Beach', 'Doral', 'Coral Gables'],
    zipCodes: ['33139', '33140', '33141', '33154', '33160', '33161', '33162', '33163', '33164', '33166'],
    tier: 2,
  },
  {
    slug: 'las-vegas-nv',
    name: 'Las Vegas',
    state: 'Nevada',
    stateAbbr: 'NV',
    tier: 2,
    intro: 'Las Vegas\'s entertainment and hospitality market plus residential growth drive demand for AV and smart home systems. Fast turnaround.',
    neighborhoods: ['Downtown', 'The Strip', 'Paradise', 'Summerlin', 'Green Valley', 'Centennial'],
    suburbs: ['Henderson', 'North Las Vegas', 'Boulder City', 'Mesquite'],
    zipCodes: ['89101', '89102', '89103', '89104', '89105', '89106', '89107', '89108', '89109', '89110'],
    tier: 2,
  },
  {
    slug: 'nashville-tn',
    name: 'Nashville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    tier: 2,
    intro: 'Nashville\'s growing music industry and booming residential market create strong demand for commercial and residential AV. Fast installs available.',
    neighborhoods: ['Downtown', 'Germantown', 'East Nashville', 'Midtown', 'Green Hills', 'Belle Meade'],
    suburbs: ['Franklin', 'Brentwood', 'Spring Hill', 'Hendersonville'],
    zipCodes: ['37201', '37202', '37203', '37204', '37205', '37206', '37207', '37208', '37209', '37210'],
    tier: 2,
  },
  {
    slug: 'kansas-city-mo',
    name: 'Kansas City',
    state: 'Missouri',
    stateAbbr: 'MO',
    tier: 2,
    intro: 'Kansas City\'s commercial growth and residential expansion drive demand for AV and smart home systems. Same-week availability.',
    neighborhoods: ['Downtown', 'Midtown', 'Westport', 'Power & Light', 'Northland', 'Southland'],
    suburbs: ['Independence', 'Lee\'s Summit', 'Overland Park', 'Olathe'],
    zipCodes: ['64101', '64102', '64103', '64104', '64105', '64106', '64111', '64112', '64113', '64114'],
    tier: 2,
  },
  {
    slug: 'charlotte-nc',
    name: 'Charlotte',
    state: 'North Carolina',
    stateAbbr: 'NC',
    tier: 2,
    intro: 'Charlotte\'s financial sector and upscale residential market drive demand for commercial AV and home automation. Fast turnaround.',
    neighborhoods: ['Downtown', 'South End', 'Uptown', 'NoDa', 'Myers Park', 'Dilworth'],
    suburbs: ['Concord', 'Huntersville', 'Matthews', 'Gastonia'],
    zipCodes: ['28202', '28203', '28204', '28205', '28206', '28207', '28208', '28209', '28210', '28211'],
    tier: 2,
  },
  {
    slug: 'orlando-fl',
    name: 'Orlando',
    state: 'Florida',
    stateAbbr: 'FL',
    tier: 2,
    intro: 'Orlando\'s tourism and entertainment industry plus residential growth drive demand for commercial and residential AV systems.',
    neighborhoods: ['Downtown', 'Lake Eustis', 'Thornton Park', 'Winter Park', 'Maitland', 'Altamonte Springs'],
    suburbs: ['Winter Springs', 'Oviedo', 'Casselberry', 'Kissimmee'],
    zipCodes: ['32801', '32802', '32803', '32804', '32805', '32806', '32807', '32808', '32809', '32810'],
    tier: 2,
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getCitiesByTier(tier: 1 | 2 | 3): City[] {
  return cities.filter((c) => c.tier === tier);
}

export function getAllCitySlugs(): string[] {
  return cities.map((c) => c.slug);
}
